spring.application.name=${APPLICATION_NAME:course-api}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DATASOURCE_DATABASE:course-api}
spring.datasource.username=${DATASOURCE_USERNAME:the0shail}
spring.datasource.password=${DATASOURCE_PASSWORD:the0shail}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security.oauth2=debug
logging.level.org.springframework.security=DEBUG

spring.jackson.property-naming-strategy=SNAKE_CASE

logging.level.org.hibernate.SQL=debug

jwt.secret=${JWT_SECRET:menya-nuzhno-zamenit-na-normalnyy-sekret-32+}
jwt.ttl-minutes=${JWT_TTL_MINUTES:15}
jwt.refresh-ttl-days=${JWT_REFRESH_TTL_DAYS:30}

